### ISSUE TITLE
"Configuration - Root OLC" get a "Attribute action failed."

### ISSUE THREAD

**Issue by ivoruetsche** [seb4itik/slapd#2]
Hi

We have there configuration, like described in the example:
```
slapd_user: openldap
slapd_group: "{{ slapd_user }}"
slapd_ssl: true
slapd_ssl_group: ssl-cert
slapd_monitor: false
slapd_monitor_admin:

slapd_modules:
  - "back_mdb"

slapd_module_path: /usr/lib/ldap
slapd_schemas: []
slapd_schema_path: /etc/ldap/schema
slapd_apparmor_file: /etc/apparmor.d/usr.sbin.slapd
slapd_config_frontend: {}

slapd_config_olc:
  olcLogLevel: 64
  olcTLSCertificateKeyFile: "/etc/ssl/private/slap_{{ inventory_hostname }}.key"
  olcTLSCACertificateFile: "/etc/ssl/private/slap_fullchain_{{ inventory_hostname }}.key"
  olcTLSCertificateFile: "/etc/ssl/certs/slap_{{ inventory_hostname }}.crt"

slapd_config_backends:
  - db_type: "mdb"
    attributes:
      olcSuffix: "dc=testcomp,dc=local"
      olcDbDirectory: "/var/lib/ldap-testcomp"
      olcRootDN: "cn=admin,dc=testcomp,dc=local"
      olcRootPW: "test,4224"
```

But we get:
```
TASK [galaxy/slapd : Configuration - Root OLC] ********************************************************************************************************************************************************************
fatal: [test01.testcomp.local]: FAILED! => {"changed": false, "details": "{'msgtype': 103, 'msgid': 6, 'result': 80, 'desc': 'Other (e.g., implementation specific) error', 'ctrls': []}", "msg": "Attribute action failed."}
```

The OS is: "Debian GNU/Linux trixie/sid"

What we missed in the configuration?

Thanks for any advice
Ivo
